#!/usr/bin/env python3
"""Transform a gova-monolith api.json manifest into the SEED.md Generated
Context block. Deterministic: output depends only on manifest content, not on
the ordering of models/endpoints within it."""

import json
import sys

_SWIFT_TYPES = {
    "int": "Int",
    "string": "String",
    "boolean": "Bool",
    "float": "Double",
    "timestamp": "Date",
}


def swift_type(field_type: str, nullable: bool) -> str:
    base = _SWIFT_TYPES.get(field_type, "String")
    return base + "?" if nullable else base


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.split("_") if part)


def render_context(manifest: dict) -> str:
    models = sorted(manifest.get("models") or [], key=lambda m: m["name"])
    endpoints = sorted(
        manifest.get("endpoints") or [],
        key=lambda e: (e["path"], e["method"]),
    )
    api_version = manifest.get("api_version", "")
    hash_ = manifest.get("hash", "")

    bearer_ready = any(e.get("kind") == "mobile_login" for e in endpoints)
    list_models = sorted(
        {e["model"] for e in endpoints if e.get("kind") == "list" and e.get("model")}
    )

    lines = []
    lines.append("### Web App Context")
    lines.append(f"Generated by /export:mobile from api.json — manifest hash {hash_}.")
    lines.append("")
    lines.append("#### API")
    lines.append(f"- api_version: {api_version}")
    lines.append(f"- Bearer (mobile) auth ready: {'yes' if bearer_ready else 'no'}")
    lines.append("")

    lines.append("#### Models")
    for m in models:
        lines.append(f"**{pascal(m['name'])}**  (table: {m['table']})")
        for f in m.get("fields", []):
            display = f["type"] + ("?" if f.get("nullable") else "")
            lines.append(f"  - {f['name']}: {display} → {swift_type(f['type'], f.get('nullable', False))}")
        lines.append("")

    lines.append("#### Resources → endpoints")
    for m in models:
        m_eps = [e for e in endpoints if e.get("model") == m["name"]]
        if not m_eps:
            continue
        lines.append(f"**{m['name']}**")
        for e in m_eps:
            lines.append(f"  - {e['method']} {e['path']}  [{e.get('kind', '')}]  auth:{'yes' if e.get('auth') else 'no'}")
        lines.append("")

    lines.append("#### Auth endpoints")
    for e in endpoints:
        if not e.get("model"):
            lines.append(f"  - {e['method']} {e['path']}  [{e.get('kind', '')}]")
    lines.append("")

    lines.append("#### Screens to generate")
    lines.append(f"  - One list screen per model with a `list` endpoint: [{', '.join(list_models)}]")
    lines.append(f"  - Login screen: {'yes' if bearer_ready else 'no'}")

    return "\n".join(lines)
