#!/usr/bin/env python3
"""Transform a gova-monolith api.json manifest into the SEED.md Generated
Context block. Deterministic: output depends only on manifest content, not on
the ordering of models/endpoints within it."""

import json
import sys

_SWIFT_TYPES = {
    "int": "Int",
    "string": "String",
    "boolean": "Bool",
    "float": "Double",
    "timestamp": "Date",
}


def swift_type(field_type: str, nullable: bool) -> str:
    base = _SWIFT_TYPES.get(field_type, "String")
    return base + "?" if nullable else base


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.split("_") if part)


def render_context(manifest: dict) -> str:
    models = sorted(manifest.get("models") or [], key=lambda m: m["name"])
    endpoints = sorted(
        manifest.get("endpoints") or [],
        key=lambda e: (e["path"], e["method"]),
    )
    api_version = manifest.get("api_version", "")
    hash_ = manifest.get("hash", "")

    bearer_ready = any(e.get("kind") == "mobile_login" for e in endpoints)
    list_models = sorted(
        {e["model"] for e in endpoints if e.get("kind") == "list" and e.get("model")}
    )

    lines = []
    lines.append("### Web App Context")
    lines.append(f"Generated by /export:mobile from api.json — manifest hash {hash_}.")
    lines.append("")
    lines.append("#### API")
    lines.append(f"- api_version: {api_version}")
    lines.append(f"- Bearer (mobile) auth ready: {'yes' if bearer_ready else 'no'}")
    lines.append("")

    lines.append("#### Models")
    for m in models:
        lines.append(f"**{pascal(m['name'])}**  (table: {m['table']})")
        for f in m.get("fields", []):
            display = f["type"] + ("?" if f.get("nullable") else "")
            lines.append(f"  - {f['name']}: {display} → {swift_type(f['type'], f.get('nullable', False))}")
        lines.append("")

    lines.append("#### Resources → endpoints")
    for m in models:
        m_eps = [e for e in endpoints if e.get("model") == m["name"]]
        if not m_eps:
            continue
        lines.append(f"**{m['name']}**")
        for e in m_eps:
            lines.append(f"  - {e['method']} {e['path']}  [{e.get('kind', '')}]  auth:{'yes' if e.get('auth') else 'no'}")
        lines.append("")

    lines.append("#### Auth endpoints")
    for e in endpoints:
        if not e.get("model"):
            lines.append(f"  - {e['method']} {e['path']}  [{e.get('kind', '')}]")
    lines.append("")

    lines.append("#### Screens to generate")
    lines.append(f"  - One list screen per model with a `list` endpoint: [{', '.join(list_models)}]")
    lines.append(f"  - Login screen: {'yes' if bearer_ready else 'no'}")

    return "\n".join(lines)


MARKER = "<!-- /export:mobile WRITES BELOW THIS LINE -->"


def splice_seed(seed_text: str, block: str) -> str:
    """Replace everything below the marker with block; preserve everything from
    the top through the marker byte-for-byte. Append the marker first if absent."""
    if MARKER in seed_text:
        head = seed_text[: seed_text.index(MARKER) + len(MARKER)]
        return head + "\n\n" + block + "\n"
    sep = "" if seed_text.endswith("\n") else "\n"
    return seed_text + sep + MARKER + "\n\n" + block + "\n"


def main(argv=None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    if len(argv) != 2:
        print("usage: export_manifest.py <api.json path> <SEED.md path>", file=sys.stderr)
        return 2
    api_path, seed_path = argv
    try:
        with open(api_path) as fh:
            manifest = json.load(fh)
    except FileNotFoundError:
        print(f"api.json not found at {api_path}", file=sys.stderr)
        return 1
    except json.JSONDecodeError as exc:
        print(f"api.json is not valid JSON: {exc}", file=sys.stderr)
        return 1

    block = render_context(manifest)
    with open(seed_path) as fh:
        seed = fh.read()
    with open(seed_path, "w") as fh:
        fh.write(splice_seed(seed, block))

    n_models = len(manifest.get("models") or [])
    n_endpoints = len(manifest.get("endpoints") or [])
    bearer = any(e.get("kind") == "mobile_login" for e in (manifest.get("endpoints") or []))
    print(f"models={n_models} endpoints={n_endpoints} bearer_auth={'yes' if bearer else 'no'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
