import unittest
from export_manifest import render_context, swift_type, pascal, splice_seed, MARKER

SAMPLE = {
    "api_version": "1.0.0",
    "hash": "sha256:abc123",
    "generated_at": "2026-07-23T00:00:00Z",
    "models": [
        {"name": "project", "table": "projects", "fields": [
            {"name": "id", "type": "int", "nullable": False},
            {"name": "name", "type": "string", "nullable": False},
            {"name": "notes", "type": "string", "nullable": True},
            {"name": "created_at", "type": "timestamp", "nullable": False},
        ]},
        {"name": "order_item", "table": "order_items", "fields": [
            {"name": "id", "type": "int", "nullable": False},
            {"name": "qty", "type": "int", "nullable": False},
            {"name": "created_at", "type": "timestamp", "nullable": False},
        ]},
        {"name": "log_category", "table": "log_categories", "fields": [
            {"name": "id", "type": "int", "nullable": False},
            {"name": "title", "type": "string", "nullable": False},
            {"name": "created_at", "type": "timestamp", "nullable": False},
        ]},
        {"name": "reminder", "table": "reminders", "fields": [
            {"name": "id", "type": "int", "nullable": False},
            {"name": "remind_at", "type": "string", "nullable": False, "format": "datetime-local"},
            {"name": "category_id", "type": "int", "nullable": False, "references": "log_category"},
            {"name": "created_at", "type": "timestamp", "nullable": False},
        ]},
    ],
    "endpoints": [
        {"method": "GET", "path": "/api/v1/order_items", "handler": "OrderItemListGET",
         "deps": ["read", "write", "cache"], "auth": False, "model": "order_item", "kind": "list"},
        {"method": "GET", "path": "/api/v1/projects", "handler": "ProjectListGET",
         "deps": ["read", "write", "cache"], "auth": False, "model": "project", "kind": "list"},
        {"method": "POST", "path": "/api/v1/auth/login_token", "handler": "MobileLoginPOST",
         "deps": ["read", "write", "cache"], "auth": False, "kind": "mobile_login"},
        {"method": "GET", "path": "/api/v1/auth/me_token", "handler": "MobileMeGET",
         "deps": ["read", "write", "cache"], "auth": False, "kind": "mobile_me"},
        {"method": "GET", "path": "/api/v1/log_categories", "handler": "LogCategoryListGET",
         "deps": ["read"], "auth": False, "model": "log_category", "kind": "list",
         "response": {"shape": "list", "model": "log_category"}},
        {"method": "GET", "path": "/api/v1/reminders", "handler": "ReminderListGET",
         "deps": ["read"], "auth": False, "model": "reminder", "kind": "list",
         "response": {"shape": "list", "model": "reminder"}},
        {"method": "POST", "path": "/api/v1/reminders", "handler": "ReminderCreatePOST",
         "deps": ["read"], "auth": False, "model": "reminder", "kind": "create",
         "request": {"shape": "object", "fields": [
             {"name": "remind_at", "type": "string", "nullable": False, "format": "datetime-local"},
             {"name": "category_id", "type": "int", "nullable": False, "references": "log_category"}]},
         "response": {"shape": "object", "model": "reminder"}},
        {"method": "POST", "path": "/api/v1/reminders/{id}/snooze", "handler": "ReminderSnoozePOST",
         "deps": ["read"], "auth": False, "kind": "custom",
         "summary": "Snooze a reminder by N minutes",
         "request": {"shape": "object", "fields": [{"name": "minutes", "type": "int", "nullable": False}]},
         "response": {"shape": "object", "model": "reminder"}},
    ],
}


class TestSwiftType(unittest.TestCase):
    def test_map(self):
        self.assertEqual(swift_type("int", False), "Int")
        self.assertEqual(swift_type("string", False), "String")
        self.assertEqual(swift_type("boolean", False), "Bool")
        self.assertEqual(swift_type("float", False), "Double")
        self.assertEqual(swift_type("timestamp", False), "Date")

    def test_nullable_is_optional(self):
        self.assertEqual(swift_type("string", True), "String?")
        self.assertEqual(swift_type("int", True), "Int?")

    def test_unknown_type_defaults_to_string(self):
        self.assertEqual(swift_type("weird", False), "String")


class TestPascal(unittest.TestCase):
    def test_single(self):
        self.assertEqual(pascal("project"), "Project")

    def test_snake(self):
        self.assertEqual(pascal("order_item"), "OrderItem")


class TestRenderContext(unittest.TestCase):
    def setUp(self):
        self.out = render_context(SAMPLE)

    def test_header_and_hash(self):
        self.assertIn("Generated by /export:mobile from api.json — manifest hash sha256:abc123.", self.out)
        self.assertIn("- api_version: 1.0.0", self.out)

    def test_bearer_ready_yes(self):
        self.assertIn("- Bearer (mobile) auth ready: yes", self.out)

    def test_models_sorted_by_name(self):
        # order_item sorts before project regardless of manifest order
        self.assertLess(self.out.index("**OrderItem**"), self.out.index("**Project**"))

    def test_nullable_field_is_optional(self):
        self.assertIn("- notes: string? → String?", self.out)

    def test_nonnullable_field(self):
        self.assertIn("- name: string → String", self.out)

    def test_timestamp_maps_to_date(self):
        self.assertIn("- created_at: timestamp → Date", self.out)

    def test_table_shown(self):
        self.assertIn("**Project**  (table: projects)", self.out)

    def test_resource_endpoints_grouped(self):
        self.assertIn("**project**", self.out)
        self.assertIn("- GET /api/v1/projects  [list]  auth:no", self.out)

    def test_auth_endpoints_section(self):
        self.assertIn("- POST /api/v1/auth/login_token  [mobile_login]", self.out)
        self.assertIn("- GET /api/v1/auth/me_token  [mobile_me]", self.out)

    def test_screens_line(self):
        self.assertIn("Top-level list screens (list endpoint, not a child): [log_category, order_item, project]", self.out)
        self.assertIn("Login screen: yes", self.out)

    def test_deterministic_regardless_of_input_order(self):
        import copy
        shuffled = copy.deepcopy(SAMPLE)
        shuffled["models"].reverse()
        shuffled["endpoints"].reverse()
        self.assertEqual(render_context(shuffled), self.out)


class TestEnrichedContract(unittest.TestCase):
    def setUp(self):
        self.out = render_context(SAMPLE)

    def test_format_hint_shown_on_field(self):
        self.assertIn("[format: datetime-local]", self.out)

    def test_reference_shown_on_field(self):
        self.assertIn("[ref → log_category]", self.out)

    def test_endpoint_shows_request_and_response(self):
        self.assertIn("request: object{remind_at:datetime-local, category_id->log_category}", self.out)
        self.assertIn("response: object(reminder)", self.out)

    def test_relationships_section(self):
        self.assertIn("#### Relationships", self.out)
        self.assertIn("`reminder` is a child of `log_category` (via `category_id`)", self.out)

    def test_custom_endpoints_section(self):
        self.assertIn("#### Custom endpoints", self.out)
        self.assertIn("POST /api/v1/reminders/{id}/snooze — Snooze a reminder by N minutes", self.out)
        self.assertIn("attach: detail  control: form", self.out)

    def test_top_level_excludes_child(self):
        # reminder is a child (has a ref) so it is NOT a top-level screen; log_category and project are.
        self.assertIn("Top-level list screens (list endpoint, not a child): [log_category, order_item, project]", self.out)

    def test_nested_screen_listed(self):
        self.assertIn("Nested: `reminder` list under `log_category` detail, filtered by `category_id`", self.out)


class TestRenderContextEmpty(unittest.TestCase):
    def test_empty_manifest(self):
        out = render_context({"api_version": "1.0.0", "hash": "sha256:0", "models": [], "endpoints": []})
        self.assertIn("- Bearer (mobile) auth ready: no", out)
        self.assertIn("Top-level list screens (list endpoint, not a child): []", out)
        self.assertIn("Login screen: no", out)
        self.assertIn("#### Relationships", out)
        self.assertIn("  - (none)", out)
        self.assertIn("#### Custom endpoints", out)


SEED_WITH_MARKER = """# iOS App Specification

## App Name
Task Manager

## Web App Path
/Users/dev/gova-monolith

---
## Generated Context
> Auto-populated by /export:mobile.

<!-- /export:mobile WRITES BELOW THIS LINE -->
### Web App Context
OLD STALE BLOCK THAT MUST BE REPLACED
"""


class TestSpliceSeed(unittest.TestCase):
    def test_preserves_developer_section_byte_for_byte(self):
        head = SEED_WITH_MARKER[: SEED_WITH_MARKER.index(MARKER) + len(MARKER)]
        out = splice_seed(SEED_WITH_MARKER, "NEW BLOCK")
        self.assertTrue(out.startswith(head))

    def test_replaces_below_marker(self):
        out = splice_seed(SEED_WITH_MARKER, "NEW BLOCK")
        self.assertIn("NEW BLOCK", out)
        self.assertNotIn("OLD STALE BLOCK", out)

    def test_idempotent(self):
        once = splice_seed(SEED_WITH_MARKER, "NEW BLOCK")
        twice = splice_seed(once, "NEW BLOCK")
        self.assertEqual(once, twice)

    def test_marker_absent_appends_marker_and_block(self):
        seed = "# Spec\n\n## App Name\nFoo\n"
        out = splice_seed(seed, "NEW BLOCK")
        self.assertTrue(out.startswith(seed))
        self.assertIn(MARKER, out)
        self.assertIn("NEW BLOCK", out)

    def test_marker_appears_exactly_once(self):
        out = splice_seed(SEED_WITH_MARKER, "NEW BLOCK")
        self.assertEqual(out.count(MARKER), 1)


if __name__ == "__main__":
    unittest.main()
