import unittest
from export_manifest import render_context, swift_type, pascal

SAMPLE = {
    "api_version": "1.0.0",
    "hash": "sha256:abc123",
    "generated_at": "2026-07-23T00:00:00Z",
    "models": [
        {"name": "project", "table": "projects", "fields": [
            {"name": "id", "type": "int", "nullable": False},
            {"name": "name", "type": "string", "nullable": False},
            {"name": "notes", "type": "string", "nullable": True},
            {"name": "created_at", "type": "timestamp", "nullable": False},
        ]},
        {"name": "order_item", "table": "order_items", "fields": [
            {"name": "id", "type": "int", "nullable": False},
            {"name": "qty", "type": "int", "nullable": False},
            {"name": "created_at", "type": "timestamp", "nullable": False},
        ]},
    ],
    "endpoints": [
        {"method": "GET", "path": "/api/v1/order_items", "handler": "OrderItemListGET",
         "deps": ["read", "write", "cache"], "auth": False, "model": "order_item", "kind": "list"},
        {"method": "GET", "path": "/api/v1/projects", "handler": "ProjectListGET",
         "deps": ["read", "write", "cache"], "auth": False, "model": "project", "kind": "list"},
        {"method": "POST", "path": "/api/v1/auth/login_token", "handler": "MobileLoginPOST",
         "deps": ["read", "write", "cache"], "auth": False, "kind": "mobile_login"},
        {"method": "GET", "path": "/api/v1/auth/me_token", "handler": "MobileMeGET",
         "deps": ["read", "write", "cache"], "auth": False, "kind": "mobile_me"},
    ],
}


class TestSwiftType(unittest.TestCase):
    def test_map(self):
        self.assertEqual(swift_type("int", False), "Int")
        self.assertEqual(swift_type("string", False), "String")
        self.assertEqual(swift_type("boolean", False), "Bool")
        self.assertEqual(swift_type("float", False), "Double")
        self.assertEqual(swift_type("timestamp", False), "Date")

    def test_nullable_is_optional(self):
        self.assertEqual(swift_type("string", True), "String?")
        self.assertEqual(swift_type("int", True), "Int?")

    def test_unknown_type_defaults_to_string(self):
        self.assertEqual(swift_type("weird", False), "String")


class TestPascal(unittest.TestCase):
    def test_single(self):
        self.assertEqual(pascal("project"), "Project")

    def test_snake(self):
        self.assertEqual(pascal("order_item"), "OrderItem")


class TestRenderContext(unittest.TestCase):
    def setUp(self):
        self.out = render_context(SAMPLE)

    def test_header_and_hash(self):
        self.assertIn("Generated by /export:mobile from api.json — manifest hash sha256:abc123.", self.out)
        self.assertIn("- api_version: 1.0.0", self.out)

    def test_bearer_ready_yes(self):
        self.assertIn("- Bearer (mobile) auth ready: yes", self.out)

    def test_models_sorted_by_name(self):
        # order_item sorts before project regardless of manifest order
        self.assertLess(self.out.index("**OrderItem**"), self.out.index("**Project**"))

    def test_nullable_field_is_optional(self):
        self.assertIn("- notes: string? → String?", self.out)

    def test_nonnullable_field(self):
        self.assertIn("- name: string → String", self.out)

    def test_timestamp_maps_to_date(self):
        self.assertIn("- created_at: timestamp → Date", self.out)

    def test_table_shown(self):
        self.assertIn("**Project**  (table: projects)", self.out)

    def test_resource_endpoints_grouped(self):
        self.assertIn("**project**", self.out)
        self.assertIn("- GET /api/v1/projects  [list]  auth:no", self.out)

    def test_auth_endpoints_section(self):
        self.assertIn("- POST /api/v1/auth/login_token  [mobile_login]", self.out)
        self.assertIn("- GET /api/v1/auth/me_token  [mobile_me]", self.out)

    def test_screens_line(self):
        self.assertIn("One list screen per model with a `list` endpoint: [order_item, project]", self.out)
        self.assertIn("Login screen: yes", self.out)

    def test_deterministic_regardless_of_input_order(self):
        import copy
        shuffled = copy.deepcopy(SAMPLE)
        shuffled["models"].reverse()
        shuffled["endpoints"].reverse()
        self.assertEqual(render_context(shuffled), self.out)


class TestRenderContextEmpty(unittest.TestCase):
    def test_empty_manifest(self):
        out = render_context({"api_version": "1.0.0", "hash": "sha256:0", "models": [], "endpoints": []})
        self.assertIn("- Bearer (mobile) auth ready: no", out)
        self.assertIn("One list screen per model with a `list` endpoint: []", out)
        self.assertIn("Login screen: no", out)


if __name__ == "__main__":
    unittest.main()
